""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"C:\Users\tauru\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
MI_DEFAULT_VARIANT = ''
MI_VARIANTS = ['scalar_rgb']
DRJIT_VERSION_REQUIREMENT = '0.4.6'
CXX_COMPILER = 'MSVC 19.43.34809.0'
